### ISSUE TITLE
I-9 Notary Authorization

### ISSUE THREAD

**Issue by amberhinds** [roadwarriorwp/rwc-employee-handbook#2]
@christophermhinds On the federal documents list it says: 

> I-9  Notary Authorization - Remote employees only. Does not need to be returned, but is required to complete I-9.

Is it accurate that we don't need a copy of this?  How do we know that it was done correctly if we don't receive a copy?  Theoretically without this, we have no way of knowing that it was really a notary who looked at the IDs and filled out the I9.

Do we also need to require copies of the identifying documents?  We did that for Ren and I belive we have to do it for everyone in order to be consistent and non discriminatory.

**Comment by christophermhinds** [comment]
This isn't a Federal document. I'll move to internal/company documents list.
